site_name: "Bits e Processadores"
theme:
  name: active-handout-theme

docs_dir: "docs-src"
site_url: https://insper.github.io/bits-e-proc/
repo_name: "Insper/bits-e-proc"
repo_url: "https://github.com/insper/bits-e-proc"

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - active-handout:
      telemetry: true
      backend_url: https://devlife-api.insper-comp.com.br/
      course_slug: 22b bits

extra:
  custom_variables:
    lab_1_groups_spreadsheet: 'https://docs.google.com/spreadsheets/d/1V1h8e0awIF-E_OVm-Vc4zupaBRAQf-PcWidCq1knw74/edit?usp=sharing'
    lab_1_mural: 'https://app.mural.co/t/elementos9119/m/elementos9119/1674526677441/31581d4e5c96eee30370b8f0896d4ed47928ff1?sender=ub569a9273c6e285461187641'
    lab_1_benchmark: 'https://docs.google.com/spreadsheets/d/1-wJcqGsZMZzgkiVMG4cb2BI__cL7_cRLNCoCHIYf-GA/edit?usp=sharing'
    lab_5_classroom: https://classroom.github.com/a/vL9MgUbs
    lab_5_points: '2 HW / 1 SW'
    lab_6_classroom: https://classroom.github.com/a/yQ34x1Xc
    lab_6_points: '1 HW / 0 SW'
    lab_10_classroom: https://classroom.github.com/a/eTzJJv1o
    lab_11_points: '0 HW / 2 SW'
    lab_11_classroom: https://classroom.github.com/a/rS4zT505

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home:
      - index: "Sobre.md"
      - "Sobre-Criterios-de-Avaliacao.md"
      - "Sobre-Rubricas.md"
  - Projetos:
      - "class/intro-proj.md"
      - "class/comb-proj.md"
      - "class/ula-proj.md"
      - "class/seq-proj.md"
      - "class/asm-proj.md"
      - 'class/assembler-proj.md'
      - "class/vmtranslator-proj.md"
      - 'class/x-proj.md'
  - Labs:
      - "class/intro-benchmark-lab.md"
      - "class/intro-lab-1.md"
      - "class/intro-lab-2.md"
      - "class/transistores-lab-1.md"
      - "class/comb-lab-1.md"
      - "class/ula-lab-1.md"
      - "class/ula-lab-2.md"
      - "class/ula-lab-4.md"
      - "class/ula-lab-3.md"
      - "class/seq-lab-1.md"
      - "class/asm-lab-1.md"
      - "class/asm-lab-2.md"
      - "class/asm-lab-3.md"
      - "class/asm-lab-4.md"
      - "class/assembler-lab-1.md"
      - "class/vm-lab-1.md"
      - "class/vmtranslator-lab-1.md"

  - Teoria:
      - "commum-content/teoria/Teoria-Dados.md"
      - "commum-content/teoria/Teoria-Algebra-Booleana.md"
      #    - "commum-content/teoria/Teoria-CMOS.md"
      - "commum-content/teoria/Teoria-RTL.md"
      - "commum-content/teoria/Teoria-Componentes.md"
      - "commum-content/teoria/Teoria-Aritmetica-Binaria.md"
      - "commum-content/teoria/Teoria-Aritmetica-Binaria-HW.md"
      - "commum-content/teoria/Teoria-ULA.md"
      - "commum-content/teoria/Teoria-Logica-Sequencial.md"
      - "commum-content/teoria/Teoria-Sequencial-Componentes.md"
      - "commum-content/teoria/Teoria-Z01.md"
      - "commum-content/teoria/Teoria-Assembly.md"
      - "commum-content/teoria/Teoria-Z01-mapadeMemoria.md"
      - "commum-content/teoria/Teoria-nasm-jump.md"
      - "commum-content/teoria/Teoria-Linguagem-de-Maquina.md"
      - "commum-content/teoria/Teoria-Assembler.md"
      - "commum-content/teoria/Teoria-Assembler-SymbolTable.md"
      - "commum-content/teoria/Teoria-vm.md"
      - "commum-content/teoria/Teoria-vm-segmentos.md"
      - "commum-content/teoria/Teoria-vm-jump.md"
      - "commum-content/teoria/Teoria-vm-funcoes.md"
      - "commum-content/teoria/Teoria-vm-memoria.md"
      - "commum-content/teoria/Vídeo Aulas (Luciano)": "Util-Video-Aulas.md"

  - MyHDL:
      - "teoria/myhdl-1.md"

  - "Z01":
      - "Resumo Assembly": "commum-content/z01/z01-Resumo-Assembly.md"
      - "Z01.1 Cheat Sheet": "commum-content/z01/z01-Cheat-Sheet.md"
      - "Instruction Set": "commum-content/z01/z01-InstructionSet.md"
      - "Resumo VM": "commum-content/z01/z01-Resumo-VM.md"

  - Exercícios:
      - "commum-content/exercicios/Exercicio-Algebra-Booleana-1.md"
      - "commum-content/exercicios/Exercicio-Algebra-Booleana-2.md"
      - "Dados Digitais - 1": https://docs.google.com/spreadsheets/d/1rN_zQqYaVI8PjAhKqEBCmY-_06I0X9dD0RddcI-miJs/edit?usp=sharing
      - "commum-content/exercicios/Exercicio-Dados-2.md"
      - "Aritmética binária - HW": https://github.com/Insper/elementos-bits-content/blob/main/exercicios/Exercicio-Aritmetica-Booleana.pdf
      - "Lógica Sequencial": "https://forms.gle/XMsFCDMYsmz1qUP86"
      - "Linguagem de Máquina": "https://github.com/Insper/elementos-bits-content/blob/main/exercicios/Linguagem_de_maquina.pdf"
      - "commum-content/exercicios/Exercicio-CPU-1.md"
      - "commum-content/exercicios/Exercicio-CPU-2.md"
      - "linguagem de máquina": commum-content/exercicios/Linguagem_de_maquina.pdf"

  - Útil:
      - "commum-content/util/Util-Comecando-novo-projeto.md"
      - "commum-content/util/Util-vixi-sou-scrum.md"
      - "commum-content/util/Util-vixi-sou-dev.md"
      - "util/util-infra.md"

  - Avaliações: "Avaliacoes.md"
#- História:
#  - 'Historia-linux.md'
